#include "calculator.hpp"

/* Numbers and Identifiers */
'num'<Num>    [0-9]+                 &scan_num;
'hex'<Num>    0x([0-9]|[A-F]|[a-f])+ &scan_hex;

/* Grammar Rules */
total<Expr>: add        &reduce_total
    ;
add<Expr>: mul
    | add '+' mul       &reduce_add_mul
    ;
mul<Expr>: 'num'
    | mul '*' 'num'     &reduce_mul_int
    ;

