#include "json.hpp"

/*******************************************************************************
 * Terminals
 */
'true'  <JsonValue>     true    &read_true;
'false' <JsonValue>     false   &read_false;
'null'  <JsonValue>     null    &read_null;

/**
 * Number with exponent.
 */
'num'<JsonValue>
    (+|-)?([0-9]+(.[0-9]*)?)((e|E)(+|-)?[0-9]+)?
    &read_num;

/**
 * String in quotes.
 * 0x20 . 0x10FFFF - '"' - '\'
 * 0x20 . 0x10FFFF - 0x22 - 0x5C
 */
'string'<JsonString>
    "([\u20-\u21]|[\u23-\u5B]|[\u5D-\u10FFFF])*"
    &read_string;

/*******************************************************************************
 * Grammar Rules
 */
json<JsonValue>
    : value         &reduce_json
    ;
value<JsonValue>
    :  object       &value_object
    |  array        &value_array
    | 'string'      &value_string
    | 'num'
    | 'true'
    | 'false'
    | 'null'
    ;
object<JsonObject>
    : '{' '}'               &object_empty
    | '{' members '}'       &object_members
    ;
members<JsonObject>
    : member                &members_reduce
    | members ',' member    &members_member
    ;
member<JsonObject>
    : 'string' ':' value    &member_reduce
    ;
array<JsonArray>
    : '[' ']'               &array_empty
    | '[' values ']'        &array_values
    ;
values<JsonArray>
    : value                 &values_reduce
    | values ',' value      &values_value
    ;
